### ISSUE TITLE
I'm not sure if this is the best standard folder structure to go with.

### ISSUE THREAD

**Issue by cyberLaVoy** [dsu-effectiveness/utHelpR#2]
https://github.com/dsu-effectiveness/utHelpR/blob/4517f95a1c9cd0bdde11e78366322c4fbcbe01ae/R/project_util.R#L19

Although, there is nothing wrong with this folder structure. 

A couple things to consider:

1. Perhaps we only want to create folders that are required by functions within this package.
2. There may be a better structure that we discover as we continue our reporting infrastructure development.

**Comment by cyberLaVoy** [comment]
There is also a potential conflict with {golem} https://github.com/ThinkR-open/golem.

If we use {golem} to generate our folder structure, this may or may not conflict with a call to this function.

**Comment by MattNickodemus** [comment]
We would only use the the folder function to generate a directory structure in a non-package, non-golem package. This would be for single data projects.
