### ISSUE TITLE
The use of the {here} package does not work for Shiny app folder structure.

### ISSUE THREAD

**Issue by cyberLaVoy** [dsu-effectiveness/utHelpR#3]
https://github.com/dsu-effectiveness/utHelpR/blob/cd2e1648f8303b249d2ea84a9c8d366b6a1e269c/R/data_import.R#L36-L42

In the context of a Shiny app, SQL code is kept in inst/sql/. This breaks a call to this function (which assumes all SQL code is in sql/ from the root directory).

**Comment by MattNickodemus** [comment]
I am having a similar issue. 

The function `get_data_from_sql_file` should be altered so that we can use it to pull from sql files that are located in non-standard places in a project. The `{utHelpR}` package assumes that the project has a directory structure where SQL scripts are located in the same directory as the .Rproj file. Please alter the function to accommodate non-standard use cases.

### Current code


```r
get_data_from_sql_file <- function(file_name, dsn) {
  conn <- get_connection_object(dsn)
  query <- read_file( here::here('sql', file_name) )
  df <- dbGetQuery(conn, query) %>%
    mung_dataframe()
  return(df)
}
```

### Possible fix

```r
get_data_from_sql_file <- function(file_name, dsn, context = 'project') {
  
  conn <- get_connection_object(dsn)
  
  # caputure query
  if (context == 'project') {
    query <- read_file( here::here('sql', file_name) )
  } else if (context == 'shiny' {
   query <- read_file(here::here('inst', 'sql', file_name) )
  } else if (context == 'sandbox' {
   query <- read_file(here::here('sandbox', 'sql', file_name) )
  } else {
    query <- read_file( file_name )
  }
  
  df <- dbGetQuery(conn, query) %>%
    mung_dataframe()
  return(df)
}
```

This would handle all of our current cases, and would keep the code in the various projects clean.

**Comment by cyberLaVoy** [comment]
### Initial Argument
I think the easiest, cleanest, and most maintainable way to do this would be to remove any folder structure dependency from the function.

There is an implementation of such a function in the package already here:
https://github.com/dsu-effectiveness/utHelpR/blob/7d0e97592e3ee0dc4f9f14611ecb7bced260e8f8/R/data_import.R#L56-L62

Note that this function doesn't use the {here} package. Rather, the function takes the entire path to the file as an argument.

### Argument Rebuttal
Although, I think that using a URL to a SQL query has led to maintenance problems downstream. So perhaps we should at least assume that the SQL is within an R project? This would essentially mean merging all of the possible implementations presented, into the following function:

### Proposed Solution
```r
get_data_from_sql_file <- function(file_path, dsn) {
  conn <- get_connection_object(dsn)
  query <- read_file( here::here(file_path) )
  df <- dbGetQuery(conn, query) %>%
    mung_dataframe()
  return(df)
}
```

### Example
```r
get_data_from_sql_file( c("path", "to", "my_awsome.sql"), "edify" )
```

This does add an extra complexity of needing to pass a character vector. But it would allow for the SQL to live anywhere within the project. So it would be suitable for any folder structure, current options or future options.

**Comment by MattNickodemus** [comment]
I am not sure I love including the full file path for all cases. I know if it only a couple key strokes

```r
get_data_from_sql_file('my_query.sql', 'sandbox') 
# VS
get_data_from_sql_file(here::here('sandbox', 'my_query.sql')
```

Even worse
```r
get_data_from_sql_file('my_query.sql')
# VS
get_data_from_sql_file(here::here('sql', 'my_query.sql')
```

but it adds up over multiple projects.

**Comment by cyberLaVoy** [comment]
I agree.

I think your implementation above, checks all of our boxes:

```r
get_data_from_sql_file <- function(file_name, dsn, context = 'project') {
  
  conn <- get_connection_object(dsn)
  
  # caputure query
  if (context == 'project') {
    query <- read_file( here::here('sql', file_name) )
  } else if (context == 'shiny' {
   query <- read_file(here::here('inst', 'sql', file_name) )
  } else if (context == 'sandbox' {
   query <- read_file(here::here('sandbox', 'sql', file_name) )
  } else {
    query <- read_file( file_name )
  }
  
  df <- dbGetQuery(conn, query) %>%
    mung_dataframe()
  return(df)
}
```

One thing to note here, is we are imposing a folder structure in 'sandbox'. Which I think is fine generally. But there may be cases where the sql file is somewhere non-standard in 'sandbox', given the nature of 'sandbox'. But I think this is okay, because the function handles that case, with the else in the conditional.

I think we should replace the following two functions with this implementation:
1.
https://github.com/dsu-effectiveness/utHelpR/blob/7d0e97592e3ee0dc4f9f14611ecb7bced260e8f8/R/data_import.R#L36
2.
https://github.com/dsu-effectiveness/utHelpR/blob/7d0e97592e3ee0dc4f9f14611ecb7bced260e8f8/R/data_import.R#L56

**Comment by MattNickodemus** [comment]
👍

**Comment by cyberLaVoy** [comment]
Function implemented in master branch.
